import type { Metadata } from "next";

/* Componentes */
import Logo from "@/components/logo-cervantes";
import TermsAndConditions from "@/components/terms-and-conditions";
import AuthImage from "@/components/pages/auth-pages/auth-image";

/* Styles */
import styles from "@/styles/layout/auth-pages/auth-pages.module.scss";

/* Bootstrap */
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={styles["authorization-pages-container"]}>
            <div className={styles["logo-container"]}>
                <Logo />
            </div>
            <div className={styles["content-container"]}>
                {children}
                <TermsAndConditions />
            </div>
            <AuthImage />
        </div>
    );
}