import type { Metadata } from "next";
import { ElmsSans, ElmsSansItalic, Montaga } from "@/lib/fonts";

/* Estilos Globales */
import "./globals.css";
import "./skeleton.scss";

/* Bootstrap */
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

/* Context */
import { ThemeProvider } from "@/context/theme-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${ElmsSans.variable} ${ElmsSansItalic.variable} ${Montaga.variable}`}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
